/**
 * Entretien professionnel — banque de questions, relances et grilles.
 *
 * Règle absolue tenue ici : l'application ne rédige jamais une expérience à la
 * place de l'utilisatrice. Les « trames » sont des cases vides accompagnées
 * d'une aide à la réflexion ; aucun exemple de vécu n'est pré-rempli.
 *
 * Le barème /20 retenu (parcours 4, motivation 4, connaissance du métier et de
 * la formation 4, analyse et posture 4, organisation et communication 4) est un
 * choix pédagogique de cette application, pas le barème d'un jury.
 */

import type { Criterion, OralQuestion } from '../types'

const C = {
  parcours: {
    id: 'parcours',
    label: 'Parcours et expériences',
    points: 4,
    evidence: [
      'Des faits précis sont cités (situations, durées, responsabilités réelles)',
      'Le rôle exact qui a été le vôtre est distingué de celui de l’équipe',
      'Aucun élément identifiant une personne accompagnée',
    ],
  },
  motivation: {
    id: 'motivation',
    label: 'Motivation et projet',
    points: 4,
    evidence: [
      'Le « pourquoi infirmière » s’appuie sur des faits vécus, pas sur des formules',
      'Le « pourquoi maintenant » est expliqué',
      'Le projet est cohérent avec le parcours décrit',
    ],
  },
  metier: {
    id: 'metier',
    label: 'Connaissance du métier et de la formation',
    points: 4,
    evidence: [
      'Les différences entre les deux métiers sont nommées concrètement',
      'La formation est connue dans ses grandes lignes (alternance cours / stages)',
      'Ce qui reste à découvrir est reconnu sans être masqué',
    ],
  },
  analyse: {
    id: 'analyse',
    label: 'Analyse et posture',
    points: 4,
    evidence: [
      'Les faits sont distingués des interprétations',
      'Une limite personnelle ou une erreur est reconnue avec ce qu’elle a appris',
      'Aucun jugement porté sur une personne accompagnée ou une collègue',
    ],
  },
  organisation: {
    id: 'organisation',
    label: 'Organisation du projet et communication',
    points: 4,
    evidence: [
      'La réponse est structurée et tient dans le temps annoncé',
      'Les contraintes concrètes sont anticipées (transport, horaires, financement)',
      'Ce qui est confirmé est distingué de ce qui reste à confirmer',
    ],
  },
} satisfies Record<string, Criterion>

/** Trame de récit d'expérience, commune aux questions qui en demandent une. */
const FRAME_RECIT = [
  { id: 'contexte', label: 'Le contexte', help: 'Où, quand, avec qui. Deux phrases suffisent. Aucun élément identifiant.' },
  { id: 'faits', label: 'Ce que vous avez observé', help: 'Des faits : ce que vous avez vu, entendu, mesuré. Pas encore d’interprétation.' },
  { id: 'role', label: 'Votre rôle exact', help: 'Ce que VOUS avez fait, distinct de ce qu’a fait l’équipe.' },
  { id: 'actions', label: 'Vos actions', help: 'Dans l’ordre. Ce que vous avez décidé, proposé, réalisé.' },
  { id: 'cooperation', label: 'La coopération', help: 'À qui avez-vous transmis, avec qui avez-vous travaillé, qu’avez-vous demandé.' },
  { id: 'resultat', label: 'Le résultat observé', help: 'Ce qui s’est passé ensuite. Y compris si le résultat n’a pas été celui espéré.' },
  { id: 'apprentissage', label: 'Ce que vous en retenez', help: 'Ce que vous feriez pareil, ce que vous feriez autrement, et pourquoi.' },
]

const FRAME_SIMPLE = [
  { id: 'idee', label: 'Votre idée principale', help: 'En une phrase : ce que vous voulez que le jury retienne.' },
  { id: 'faits', label: 'Les faits qui l’appuient', help: 'Deux ou trois éléments concrets tirés de votre expérience.' },
  { id: 'limite', label: 'Une limite ou une question ouverte', help: 'Ce que vous ne savez pas encore, ou ce qui reste à confirmer.' },
]

type Spec = {
  id: string
  skill: string
  axis: string
  q: string
  level?: 'decouverte' | 'entrainement' | 'epreuve'
  follow: string[]
  looks: string[]
  avoid: string[]
  frame?: typeof FRAME_RECIT
  crit: Criterion[]
  sec?: number
}

const build = (s: Spec): OralQuestion => ({
  id: s.id,
  skillId: s.skill,
  axis: s.axis,
  question: s.q,
  level: s.level ?? 'entrainement',
  followUps: s.follow,
  looksFor: s.looks,
  avoid: s.avoid,
  frame: s.frame ?? FRAME_SIMPLE,
  criteria: s.crit,
  seconds: s.sec ?? 180,
  review: 'relu-par-le-modele',
})

export const ORAL_QUESTIONS: OralQuestion[] = [
  // ---------------------------------------------------------------- O01 ---
  build({
    id: 'O01-1',
    skill: 'O01',
    axis: 'Présentation',
    q: 'Présentez-vous en deux minutes.',
    level: 'decouverte',
    follow: [
      'Vous avez évoqué votre poste actuel : depuis combien de temps l’occupez-vous ?',
      'Qu’est-ce qui, dans ce que vous venez de dire, explique le mieux votre projet ?',
      'Si vous ne deviez garder qu’un élément de votre parcours, lequel choisiriez-vous ?',
    ],
    looks: [
      'Un ordre lisible : qui vous êtes professionnellement, votre parcours, votre projet',
      'Des faits datés plutôt qu’une liste de qualités',
      'Une durée tenue : deux minutes, ni trente secondes ni cinq minutes',
    ],
    avoid: [
      'Réciter un CV chronologique sans hiérarchie',
      'Commencer par votre vie personnelle',
      'Énumérer des qualités sans les illustrer',
    ],
    crit: [C.parcours, C.organisation],
    sec: 120,
  }),
  build({
    id: 'O01-2',
    skill: 'O01',
    axis: 'Présentation',
    q: 'Quels éléments de votre parcours expliquent le mieux votre projet d’entrer en formation infirmière ?',
    follow: [
      'Pouvez-vous donner une situation précise qui illustre cela ?',
      'À quel moment avez-vous su que vous vouliez aller plus loin ?',
    ],
    looks: ['Un lien explicite entre le parcours et le projet', 'Au moins un fait concret', 'Une progression, pas une simple accumulation'],
    avoid: ['Rester sur des généralités', 'Dire seulement « j’aime le contact humain »'],
    crit: [C.parcours, C.motivation],
  }),
  build({
    id: 'O01-3',
    skill: 'O01',
    axis: 'Présentation',
    q: 'Présentez-vous en cinq minutes, en développant deux expériences marquantes.',
    level: 'epreuve',
    follow: [
      'Vous avez développé deux expériences : laquelle vous a le plus transformée, et pourquoi ?',
      'Qu’est-ce que la seconde vous a appris que la première ne vous avait pas appris ?',
    ],
    looks: ['Une structure tenue sur cinq minutes', 'Deux expériences distinctes, pas deux variantes de la même', 'Un fil conducteur vers le projet'],
    avoid: ['Perdre le fil', 'Répéter la même idée sous deux formes', 'Dépasser largement le temps'],
    frame: FRAME_RECIT,
    crit: [C.parcours, C.analyse, C.organisation],
    sec: 300,
  }),
  build({
    id: 'O01-4',
    skill: 'O01',
    axis: 'Présentation',
    q: 'Comment décririez-vous votre métier actuel à quelqu’un qui ne le connaît pas ?',
    follow: ['Qu’est-ce qui, dans ce métier, est le plus mal compris de l’extérieur ?', 'Quelle part de votre travail est la plus invisible ?'],
    looks: ['Une description concrète, avec des actes réels', 'La dimension relationnelle ET technique', 'Le travail en équipe'],
    avoid: ['Minimiser son propre métier', 'Le réduire aux gestes techniques'],
    crit: [C.parcours, C.metier],
  }),
  build({
    id: 'O01-5',
    skill: 'O01',
    axis: 'Présentation',
    q: 'Présentez-vous en trois minutes, sans parler de vos diplômes.',
    level: 'epreuve',
    follow: ['Comment avez-vous appris ce que vous savez faire ?', 'Qu’est-ce que l’expérience vous a apporté qu’une formation n’aurait pas donné ?'],
    looks: ['Une présentation fondée sur l’expérience et les compétences', 'Des exemples concrets à la place des titres', 'Une assurance tranquille'],
    avoid: ['Se justifier de ne pas avoir de diplôme', 'Rester bloquée sur la contrainte de l’exercice'],
    crit: [C.parcours, C.analyse],
    sec: 180,
  }),

  // ---------------------------------------------------------------- O02 ---
  build({
    id: 'O02-1',
    skill: 'O02',
    axis: 'Motivation',
    q: 'Pourquoi souhaitez-vous devenir infirmière ?',
    level: 'decouverte',
    follow: [
      'Qu’est-ce qui vous empêche aujourd’hui de faire ce que vous voudriez faire ?',
      'Pouvez-vous citer une situation où vous avez ressenti cette limite ?',
      'Qu’attendez-vous de différent par rapport à votre rôle actuel ?',
    ],
    looks: ['Une motivation appuyée sur des situations vécues', 'Une différence clairement nommée entre les deux métiers', 'Pas de dévalorisation du métier actuel'],
    avoid: ['« J’aime aider les gens » sans développement', '« Pour évoluer » sans dire vers quoi', 'Dévaloriser le métier d’aide-soignante'],
    crit: [C.motivation, C.metier],
  }),
  build({
    id: 'O02-2',
    skill: 'O02',
    axis: 'Motivation',
    q: 'Pourquoi maintenant, et pas il y a cinq ans ou dans cinq ans ?',
    follow: ['Qu’est-ce qui a changé récemment ?', 'Qu’est-ce qui vous a retenue jusqu’ici ?'],
    looks: ['Une explication du moment choisi', 'Des éléments concrets : maturité professionnelle, organisation, soutien de l’employeur'],
    avoid: ['« C’est le bon moment » sans explication', 'Attribuer la décision uniquement à une circonstance extérieure'],
    crit: [C.motivation, C.organisation],
  }),
  build({
    id: 'O02-3',
    skill: 'O02',
    axis: 'Motivation',
    q: 'Qu’attendez-vous du métier d’infirmière que vous ne trouvez pas dans le vôtre ?',
    follow: ['Et qu’allez-vous perdre en changeant de métier ?', 'Comment vivrez-vous ce changement de place dans l’équipe ?'],
    looks: ['Des attentes précises : responsabilité, raisonnement clinique, suivi', 'La conscience de ce qui sera perdu aussi'],
    avoid: ['Ne voir que des avantages', 'Parler uniquement du salaire ou du statut'],
    crit: [C.motivation, C.analyse],
  }),
  build({
    id: 'O02-4',
    skill: 'O02',
    axis: 'Motivation',
    q: 'Qu’est-ce qui vous plaît le moins dans le métier d’infirmière tel que vous le connaissez ?',
    level: 'epreuve',
    follow: ['Comment comptez-vous faire avec cela ?', 'Est-ce que cela remet en cause votre projet ?'],
    looks: ['Une réponse honnête, qui ne fuit pas la question', 'Une difficulté réelle nommée', 'Une stratégie pour y faire face'],
    avoid: ['« Rien, tout me plaît »', 'Une réponse qui révèle une méconnaissance du métier'],
    crit: [C.motivation, C.analyse, C.metier],
  }),
  build({
    id: 'O02-5',
    skill: 'O02',
    axis: 'Motivation',
    q: 'Si vous n’étiez pas admise cette année, que feriez-vous ?',
    level: 'epreuve',
    follow: ['Qu’est-ce que cela changerait à votre préparation ?', 'Qu’auriez-vous appris de cette première tentative ?'],
    looks: ['Une réponse posée, sans dramatisation', 'Une capacité à envisager la suite', 'Un projet qui ne dépend pas d’une seule tentative'],
    avoid: ['« Je n’y pense pas »', 'Une réaction de découragement', 'Une réponse qui suggère que le projet n’est pas solide'],
    crit: [C.motivation, C.analyse],
  }),

  // ---------------------------------------------------------------- O03 ---
  build({
    id: 'O03-1',
    skill: 'O03',
    axis: 'Connaissance du métier',
    q: 'Quelles différences voyez-vous entre le rôle d’une aide-soignante et celui d’une infirmière ?',
    level: 'decouverte',
    follow: [
      'Pouvez-vous donner un exemple concret de ce que fait l’infirmière et que vous ne faites pas ?',
      'Sur quoi travaillez-vous ensemble au quotidien ?',
    ],
    looks: [
      'Des exemples concrets plutôt qu’une liste théorique',
      'La notion de responsabilité et de décision',
      'La collaboration, pas une hiérarchie simpliste',
    ],
    avoid: ['Réduire la différence aux gestes techniques', 'Présenter l’aide-soignante comme une simple exécutante'],
    crit: [C.metier, C.parcours],
  }),
  build({
    id: 'O03-2',
    skill: 'O03',
    axis: 'Connaissance du métier',
    q: 'Comment distinguez-vous la collaboration d’un dépassement de compétence ?',
    follow: ['Avez-vous déjà été dans une situation limite ?', 'Qu’avez-vous fait ?'],
    looks: ['Une limite claire, énoncée sans hésitation', 'Un exemple vécu', 'Le réflexe de transmettre plutôt que de décider seule'],
    avoid: ['Flouter la limite', 'Raconter un dépassement sans le reconnaître comme tel'],
    frame: FRAME_RECIT,
    crit: [C.metier, C.analyse],
  }),
  build({
    id: 'O03-3',
    skill: 'O03',
    axis: 'Connaissance du métier',
    q: 'Quelles responsabilités identifiez-vous chez une infirmière ?',
    follow: ['Laquelle vous semble la plus lourde ?', 'Comment vous y préparez-vous ?'],
    looks: ['Responsabilité de surveillance, de décision, de transmission, d’encadrement', 'La conscience de la dimension juridique'],
    avoid: ['Une vision uniquement technique', 'Ignorer la responsabilité professionnelle'],
    crit: [C.metier, C.analyse],
  }),
  build({
    id: 'O03-4',
    skill: 'O03',
    axis: 'Connaissance du métier',
    q: 'Qu’appelle-t-on le rôle propre de l’infirmière ?',
    follow: ['Pouvez-vous en donner un exemple ?', 'Comment s’articule-t-il avec le rôle sur prescription ?'],
    looks: ['Une distinction entre ce qui relève de l’initiative de l’infirmière et ce qui relève de la prescription', 'Un exemple concret'],
    avoid: ['Affirmer une définition réglementaire précise sans en être sûre', 'Confondre les deux registres'],
    crit: [C.metier],
  }),
  build({
    id: 'O03-5',
    skill: 'O03',
    axis: 'Connaissance du métier',
    q: 'Selon vous, qu’est-ce qui sera le plus difficile dans le passage d’un métier à l’autre ?',
    level: 'epreuve',
    follow: ['Comment allez-vous vous y préparer ?', 'Qui pourra vous aider sur ce point précis ?'],
    looks: ['Une difficulté identifiée honnêtement', 'La conscience du changement de posture dans l’équipe', 'Un plan, même simple'],
    avoid: ['« Rien ne sera difficile »', 'Une difficulté citée sans aucune piste'],
    crit: [C.metier, C.analyse, C.organisation],
  }),

  // ---------------------------------------------------------------- O04 ---
  build({
    id: 'O04-1',
    skill: 'O04',
    axis: 'Expérience',
    q: 'Décrivez une situation professionnelle qui vous a fait progresser.',
    level: 'decouverte',
    follow: ['Quel a été votre rôle exact ?', 'Qu’avez-vous fait différemment ensuite ?', 'Qui avez-vous sollicité ?'],
    looks: ['Un récit structuré : contexte, rôle, actions, résultat, apprentissage', 'Des faits avant les interprétations', 'Un apprentissage explicite'],
    avoid: ['Raconter sans dire ce que vous en avez tiré', 'Donner un élément identifiant une personne', 'Attribuer à l’équipe ce que vous avez fait, ou l’inverse'],
    frame: FRAME_RECIT,
    crit: [C.parcours, C.analyse],
    sec: 240,
  }),
  build({
    id: 'O04-2',
    skill: 'O04',
    axis: 'Expérience',
    q: 'Racontez une situation où vous avez dû faire face à un imprévu.',
    follow: ['Comment avez-vous priorisé ?', 'Qu’auriez-vous fait si vous aviez été seule ?'],
    looks: ['Une méthode de priorisation visible', 'La sollicitation de l’équipe', 'Un retour réflexif'],
    avoid: ['Décrire un héroïsme individuel', 'Omettre la transmission'],
    frame: FRAME_RECIT,
    crit: [C.analyse, C.organisation],
    sec: 240,
  }),
  build({
    id: 'O04-3',
    skill: 'O04',
    axis: 'Expérience',
    q: 'Décrivez une situation où votre observation a changé quelque chose pour une personne accompagnée.',
    follow: ['Qu’aviez-vous remarqué précisément ?', 'À qui l’avez-vous transmis, et comment ?'],
    looks: ['Une observation factuelle et précise', 'Une transmission décrite', 'Un effet concret'],
    avoid: ['Rester vague sur ce qui a été observé', 'Sauter l’étape de la transmission'],
    frame: FRAME_RECIT,
    crit: [C.parcours, C.analyse],
    sec: 240,
  }),
  build({
    id: 'O04-4',
    skill: 'O04',
    axis: 'Expérience',
    q: 'Racontez une situation d’accompagnement d’un proche ou d’une famille.',
    follow: ['Qu’est-ce qui était difficile pour eux ?', 'Qu’avez-vous pu faire, et qu’est-ce qui dépassait votre rôle ?'],
    looks: ['La prise en compte de l’entourage', 'La limite du rôle clairement située', 'Une orientation vers le professionnel compétent'],
    avoid: ['Prendre en charge ce qui relève d’un autre professionnel', 'Juger la famille'],
    frame: FRAME_RECIT,
    crit: [C.parcours, C.analyse, C.metier],
    sec: 240,
  }),
  build({
    id: 'O04-5',
    skill: 'O04',
    axis: 'Expérience',
    q: 'Décrivez une journée de travail type, en expliquant comment vous l’organisez.',
    level: 'epreuve',
    follow: ['Comment adaptez-vous votre organisation quand elle est perturbée ?', 'Qu’est-ce qui passe en premier, et pourquoi ?'],
    looks: ['Une organisation explicite', 'Des critères de priorisation', 'La place de l’équipe'],
    avoid: ['Une liste de tâches sans logique', 'Ne pas mentionner les transmissions'],
    crit: [C.organisation, C.parcours],
    sec: 240,
  }),

  // ---------------------------------------------------------------- O05 ---
  build({
    id: 'O05-1',
    skill: 'O05',
    axis: 'Relation',
    q: 'Comment adaptez-vous votre communication face à une personne qui a des difficultés à comprendre ?',
    level: 'decouverte',
    follow: ['Comment vérifiez-vous qu’elle a compris ?', 'Que faites-vous si elle n’a pas compris ?'],
    looks: ['Phrases courtes, vocabulaire simple, supports, temps laissé', 'Une vérification par reformulation', 'Pas d’infantilisation'],
    avoid: ['Parler plus fort comme unique adaptation', 'Demander « vous avez compris ? » et s’en contenter', 'S’adresser à l’accompagnant plutôt qu’à la personne'],
    crit: [C.analyse, C.organisation],
  }),
  build({
    id: 'O05-2',
    skill: 'O05',
    axis: 'Relation',
    q: 'Une personne refuse un soin. Comment réagissez-vous ?',
    follow: ['Et si elle refuse encore le lendemain ?', 'À quel moment transmettez-vous ?'],
    looks: ['Le refus reconnu comme un droit', 'La recherche de la raison du refus', 'Une proposition alternative et une transmission'],
    avoid: ['Insister jusqu’à obtenir un accord', 'Abandonner sans rien transmettre', 'Interpréter le refus comme une opposition personnelle'],
    crit: [C.analyse, C.metier],
  }),
  build({
    id: 'O05-3',
    skill: 'O05',
    axis: 'Relation',
    q: 'Racontez une situation où la communication a été difficile. Qu’avez-vous fait ?',
    follow: ['Qu’est-ce qui, avec le recul, aurait pu aider plus tôt ?', 'Avez-vous demandé de l’aide ?'],
    looks: ['Des faits, pas des jugements', 'Une adaptation tentée', 'Un recul honnête'],
    avoid: ['Attribuer la difficulté uniquement à la personne', 'Présenter une réussite sans difficulté'],
    frame: FRAME_RECIT,
    crit: [C.analyse, C.parcours],
    sec: 240,
  }),
  build({
    id: 'O05-4',
    skill: 'O05',
    axis: 'Relation',
    q: 'Comment faites-vous quand une personne exprime de la colère envers vous ?',
    follow: ['Comment distinguez-vous ce qui vous vise de ce qui vise la situation ?', 'Qu’est-ce que vous faites après ?'],
    looks: ['Une prise de distance professionnelle sans froideur', 'La recherche de ce qui est en jeu', 'La transmission et, si besoin, le relais par une collègue'],
    avoid: ['Répondre sur le même registre', 'Prendre la colère comme une attaque personnelle', 'Faire comme si de rien n’était'],
    crit: [C.analyse, C.organisation],
  }),
  build({
    id: 'O05-5',
    skill: 'O05',
    axis: 'Relation',
    q: 'Une personne vous confie quelque chose et vous demande de n’en parler à personne. Que faites-vous ?',
    level: 'epreuve',
    follow: ['Et si ce qu’elle vous confie signale un danger ?', 'Comment le lui expliquez-vous ?'],
    looks: [
      'La distinction entre confidentialité et secret partagé au sein de l’équipe de soin',
      'La transparence : dire à la personne ce qui sera transmis et pourquoi',
      'L’obligation de signalement en cas de danger',
    ],
    avoid: ['Promettre un silence absolu', 'Transmettre sans le dire à la personne'],
    crit: [C.metier, C.analyse],
  }),

  // ---------------------------------------------------------------- O06 ---
  build({
    id: 'O06-1',
    skill: 'O06',
    axis: 'Équipe',
    q: 'Comment transmettez-vous une information importante à l’équipe ?',
    level: 'decouverte',
    follow: ['À l’oral ou à l’écrit ?', 'Comment vous assurez-vous que l’information est arrivée ?'],
    looks: ['La trace écrite', 'Des faits précis et datés', 'Une vérification de la réception'],
    avoid: ['Une transmission uniquement orale dans un couloir', 'Des appréciations à la place des faits'],
    crit: [C.organisation, C.metier],
  }),
  build({
    id: 'O06-2',
    skill: 'O06',
    axis: 'Équipe',
    q: 'Vous n’êtes pas d’accord avec une décision prise par une collègue. Que faites-vous ?',
    follow: ['Et si la décision vous paraît risquée pour la personne accompagnée ?', 'À qui vous adressez-vous ?'],
    looks: ['Un désaccord exprimé au bon endroit et au bon moment', 'Des arguments factuels', 'L’escalade vers l’encadrement si un risque existe'],
    avoid: ['Se taire par crainte du conflit', 'Contester devant la personne accompagnée', 'Régler le désaccord dans le dos de la collègue'],
    crit: [C.analyse, C.organisation],
  }),
  build({
    id: 'O06-3',
    skill: 'O06',
    axis: 'Équipe',
    q: 'Vous constatez qu’une erreur a été commise. Comment réagissez-vous ?',
    follow: ['Et si l’erreur est la vôtre ?', 'Que faites-vous pour qu’elle ne se reproduise pas ?'],
    looks: ['Le signalement immédiat, sans chercher un coupable', 'La priorité donnée à la personne concernée', 'Une réflexion sur les causes d’organisation'],
    avoid: ['Dissimuler', 'Chercher un responsable avant de sécuriser la situation', 'Présenter l’erreur comme impossible'],
    crit: [C.metier, C.analyse],
  }),
  build({
    id: 'O06-4',
    skill: 'O06',
    axis: 'Équipe',
    q: 'Comment travaillez-vous avec les autres professionnels autour d’une même personne ?',
    follow: ['Avec qui travaillez-vous le plus ?', 'Qu’est-ce qui rend cette coopération difficile parfois ?'],
    looks: ['Une connaissance des rôles de chacun', 'Des exemples concrets de coopération', 'La conscience des points de rupture'],
    avoid: ['Une vision cloisonnée', 'Critiquer les autres professions'],
    crit: [C.metier, C.organisation],
  }),
  build({
    id: 'O06-5',
    skill: 'O06',
    axis: 'Équipe',
    q: 'En formation, vous serez en stage dans des équipes qui ne vous connaissent pas. Comment vous y prendrez-vous ?',
    level: 'epreuve',
    follow: ['Comment ferez-vous valoir votre expérience sans gêner ?', 'Comment accepterez-vous d’être en position d’apprenante ?'],
    looks: ['Une posture d’apprenante assumée', 'L’expérience présentée comme un appui, non comme une autorité', 'Le souci de s’intégrer'],
    avoid: ['« Je sais déjà faire »', 'Une posture d’effacement complet de l’expérience'],
    crit: [C.analyse, C.organisation, C.metier],
  }),

  // ---------------------------------------------------------------- O07 ---
  build({
    id: 'O07-1',
    skill: 'O07',
    axis: 'Reprise d’études',
    q: 'Comment allez-vous vous organiser pour reprendre des études ?',
    level: 'decouverte',
    follow: ['Combien d’heures par semaine ?', 'Qu’est-ce que vous allez devoir arrêter ?'],
    looks: ['Un plan concret et réaliste', 'La conscience des renoncements nécessaires', 'Des appuis identifiés'],
    avoid: ['« Je m’organiserai »', 'Un plan irréaliste qui ignore les contraintes'],
    crit: [C.organisation, C.motivation],
  }),
  build({
    id: 'O07-2',
    skill: 'O07',
    axis: 'Reprise d’études',
    q: 'Quel est votre point faible sur le plan scolaire, et comment le travaillez-vous ?',
    follow: ['Qu’avez-vous déjà mis en place ?', 'Comment saurez-vous que vous progressez ?'],
    looks: ['Une difficulté nommée sans détour', 'Une action déjà engagée', 'Un critère de progrès'],
    avoid: ['« Je n’ai pas de point faible »', 'Une difficulté citée sans aucune action'],
    crit: [C.analyse, C.organisation],
  }),
  build({
    id: 'O07-3',
    skill: 'O07',
    axis: 'Reprise d’études',
    q: 'Comment demandez-vous de l’aide quand vous ne comprenez pas quelque chose ?',
    follow: ['Avez-vous un exemple récent ?', 'Qu’est-ce qui vous empêche parfois de demander ?'],
    looks: ['Une capacité à demander sans le vivre comme un échec', 'Un exemple concret', 'L’identification d’interlocuteurs'],
    avoid: ['« Je me débrouille toujours seule »', 'Une réponse qui suggère un isolement'],
    crit: [C.analyse, C.organisation],
  }),
  build({
    id: 'O07-4',
    skill: 'O07',
    axis: 'Reprise d’études',
    q: 'Vous n’avez pas le baccalauréat. En quoi cela change-t-il votre préparation ?',
    level: 'epreuve',
    follow: ['Qu’avez-vous fait pour combler ce qui pouvait manquer ?', 'Qu’est-ce que votre expérience vous apporte que le baccalauréat n’apporte pas ?'],
    looks: [
      'Une réponse factuelle, sans justification excessive',
      'Des actions concrètes de remise à niveau',
      'La valorisation de l’expérience professionnelle, sans opposition stérile',
    ],
    avoid: ['S’excuser', 'Minimiser l’exigence académique de la formation', 'Dévaloriser les personnes titulaires du baccalauréat'],
    crit: [C.motivation, C.analyse, C.organisation],
  }),
  build({
    id: 'O07-5',
    skill: 'O07',
    axis: 'Reprise d’études',
    q: 'Comment réviserez-vous pendant la formation, sachant qu’il y aura des stages ?',
    follow: ['Comment protégerez-vous des temps de travail personnel ?', 'Que ferez-vous en période de forte charge ?'],
    looks: ['Une méthode de travail décrite', 'La régularité plutôt que l’intensité de dernière minute', 'Un plan de repli'],
    avoid: ['Un planning théorique irréaliste', 'Ne pas envisager les périodes difficiles'],
    crit: [C.organisation, C.analyse],
  }),

  // ---------------------------------------------------------------- O08 ---
  build({
    id: 'O08-1',
    skill: 'O08',
    axis: 'Réalisme du projet',
    q: 'Comment votre formation sera-t-elle financée ?',
    level: 'decouverte',
    follow: ['Ce financement est-il confirmé par écrit ?', 'Que se passe-t-il s’il ne l’est pas ?'],
    looks: [
      'Une distinction nette entre soutien de l’employeur et financement confirmé',
      'Ce qui est écrit et ce qui ne l’est pas',
      'Une solution de repli envisagée',
    ],
    avoid: ['Présenter un soutien oral comme un financement acquis', '« Mon employeur est d’accord » sans précision'],
    crit: [C.organisation, C.motivation],
  }),
  build({
    id: 'O08-2',
    skill: 'O08',
    axis: 'Réalisme du projet',
    q: 'Quelles contraintes de transport et d’organisation avez-vous anticipées ?',
    follow: ['Et pour les stages, qui peuvent être éloignés ?', 'Et pour les horaires décalés ?'],
    looks: ['Des trajets réellement estimés', 'La prise en compte des stages, pas seulement des cours', 'Des solutions concrètes'],
    avoid: ['« Je m’adapterai »', 'Ne penser qu’au lieu de formation'],
    crit: [C.organisation],
  }),
  build({
    id: 'O08-3',
    skill: 'O08',
    axis: 'Réalisme du projet',
    q: 'Qu’est-ce que votre employeur a précisément accepté ?',
    follow: ['Frais pédagogiques, rémunération, autorisation d’absence : que couvre l’accord ?', 'Y a-t-il une contrepartie d’engagement ?'],
    looks: ['Une réponse précise, point par point', 'Ce qui reste à confirmer, dit comme tel'],
    avoid: ['Une réponse vague', 'Affirmer un accord dont le contenu n’est pas connu'],
    crit: [C.organisation, C.analyse],
  }),
  build({
    id: 'O08-4',
    skill: 'O08',
    axis: 'Réalisme du projet',
    q: 'Comment allez-vous concilier formation et vie personnelle ?',
    follow: ['Qui peut vous appuyer concrètement ?', 'Qu’avez-vous déjà organisé ?'],
    looks: ['Des appuis nommés', 'Une organisation déjà amorcée', 'La reconnaissance de la difficulté'],
    avoid: ['Prétendre que tout sera simple', 'Détailler des éléments privés sans rapport avec le projet'],
    crit: [C.organisation, C.analyse],
  }),
  build({
    id: 'O08-5',
    skill: 'O08',
    axis: 'Réalisme du projet',
    q: 'Que ferez-vous si votre situation change en cours de formation : déménagement, problème de santé, changement d’employeur ?',
    level: 'epreuve',
    follow: ['Avez-vous identifié qui contacter dans ces cas-là ?', 'Qu’est-ce qui serait le plus difficile à absorber ?'],
    looks: ['Une capacité à envisager l’imprévu sans se décourager', 'Des interlocuteurs identifiés', 'Une hiérarchisation des risques'],
    avoid: ['« Cela n’arrivera pas »', 'Une réponse qui révèle une fragilité non anticipée'],
    crit: [C.organisation, C.analyse],
  }),

  // ---------------------------------------------------------------- O09 ---
  build({
    id: 'O09-1',
    skill: 'O09',
    axis: 'Connaissance de la formation',
    q: 'Que savez-vous de l’organisation de la formation infirmière ?',
    level: 'decouverte',
    follow: ['Comment s’articulent les cours et les stages ?', 'Qu’est-ce que vous ignorez encore et que vous aimeriez savoir ?'],
    looks: ['La durée et l’alternance cours / stages', 'La notion de compétences à valider', 'Une reconnaissance honnête de ce qui reste à découvrir'],
    avoid: ['Affirmer des chiffres précis dont vous n’êtes pas sûre', 'Prétendre tout connaître'],
    crit: [C.metier, C.motivation],
  }),
  build({
    id: 'O09-2',
    skill: 'O09',
    axis: 'Connaissance de la formation',
    q: 'Qu’attendez-vous des stages ?',
    follow: ['Quel type de stage vous inquiète le plus ?', 'Quel type de stage vous attire le plus ?'],
    looks: ['Une attente d’apprentissage, pas seulement de mise en pratique', 'La conscience de la diversité des terrains', 'Une honnêteté sur les appréhensions'],
    avoid: ['Ne vouloir qu’un seul type de service', 'Présenter le stage comme une formalité'],
    crit: [C.metier, C.analyse],
  }),
  build({
    id: 'O09-3',
    skill: 'O09',
    axis: 'Connaissance de la formation',
    q: 'Comment vous êtes-vous renseignée sur la formation et sur la sélection ?',
    follow: ['Qui avez-vous contacté ?', 'Qu’est-ce qui reste à confirmer ?'],
    looks: ['Des démarches concrètes : appels, courriels, sources officielles', 'La distinction entre information confirmée et information à vérifier'],
    avoid: ['Se fonder uniquement sur des témoignages', 'Affirmer des dates non confirmées'],
    crit: [C.organisation, C.motivation],
  }),
  build({
    id: 'O09-4',
    skill: 'O09',
    axis: 'Connaissance de la formation',
    q: 'Qu’est-ce qui, dans la formation, vous semble le plus exigeant ?',
    follow: ['Comment vous y préparez-vous dès maintenant ?'],
    looks: ['Une exigence identifiée : rythme, sciences, écrits, raisonnement clinique', 'Une préparation déjà engagée'],
    avoid: ['Une réponse générale', 'Minimiser l’exigence'],
    crit: [C.metier, C.organisation],
  }),
  build({
    id: 'O09-5',
    skill: 'O09',
    axis: 'Connaissance de la formation',
    q: 'Connaissez-vous le parcours spécifique destiné aux aides-soignantes expérimentées ?',
    level: 'epreuve',
    follow: ['Savez-vous à quelles conditions il est ouvert ?', 'Avez-vous vérifié votre situation auprès de l’institut ?'],
    looks: [
      'Une connaissance de l’existence de ce parcours',
      'La prudence sur les conditions exactes, à vérifier auprès de l’institut',
      'Une démarche de vérification engagée ou prévue',
    ],
    avoid: ['Affirmer être éligible sans vérification', 'Confondre ce parcours avec la sélection ordinaire'],
    crit: [C.metier, C.organisation, C.analyse],
  }),

  // ---------------------------------------------------------------- O10 ---
  build({
    id: 'O10-1',
    skill: 'O10',
    axis: 'Prise de recul',
    q: 'Racontez une situation où vous vous êtes trompée. Qu’en avez-vous tiré ?',
    follow: ['Qu’avez-vous fait immédiatement après ?', 'Qu’est-ce qui a changé dans votre pratique ?'],
    looks: ['Une erreur réelle, reconnue sans dramatisation', 'Les actions de rattrapage et la transmission', 'Un changement concret ensuite'],
    avoid: ['Une fausse erreur (« je suis trop perfectionniste »)', 'Une erreur racontée sans apprentissage', 'Reporter la faute sur autrui'],
    frame: FRAME_RECIT,
    crit: [C.analyse, C.metier],
    sec: 240,
  }),
  build({
    id: 'O10-2',
    skill: 'O10',
    axis: 'Prise de recul',
    q: 'Quelle limite personnelle avez-vous identifiée dans votre pratique ?',
    follow: ['Comment la gérez-vous au quotidien ?', 'Est-ce que cela a évolué ?'],
    looks: ['Une limite précise, professionnelle', 'Une stratégie d’adaptation', 'Une évolution dans le temps'],
    avoid: ['Une limite de façade', 'Une limite qui serait rédhibitoire sans aucune gestion'],
    crit: [C.analyse],
  }),
  build({
    id: 'O10-3',
    skill: 'O10',
    axis: 'Prise de recul',
    q: 'Qu’est-ce qui vous met le plus en difficulté émotionnellement dans votre travail ?',
    follow: ['Comment faites-vous avec cela ?', 'À qui en parlez-vous ?'],
    looks: ['Une réponse authentique et mesurée', 'Des ressources identifiées : équipe, temps d’échange, encadrement', 'Une distinction entre être touchée et être débordée'],
    avoid: ['« Rien ne me touche »', 'Une réponse qui suggère une absence totale de recul'],
    crit: [C.analyse, C.organisation],
  }),
  build({
    id: 'O10-4',
    skill: 'O10',
    axis: 'Prise de recul',
    q: 'Si vous pouviez recommencer une situation professionnelle, laquelle choisiriez-vous et que feriez-vous autrement ?',
    level: 'epreuve',
    follow: ['Qu’est-ce qui vous a empêchée de faire ainsi sur le moment ?', 'Qu’avez-vous mis en place depuis ?'],
    looks: ['Une analyse précise du moment de bascule', 'La reconnaissance des contraintes du moment', 'Un apprentissage transférable'],
    avoid: ['Une autocritique stérile', 'Une réponse qui refait l’histoire sans analyse'],
    frame: FRAME_RECIT,
    crit: [C.analyse, C.parcours],
    sec: 240,
  }),
  build({
    id: 'O10-5',
    skill: 'O10',
    axis: 'Prise de recul',
    q: 'Qu’est-ce que votre expérience d’aide-soignante pourrait vous faire manquer en tant qu’infirmière ?',
    level: 'epreuve',
    follow: ['Comment éviterez-vous cet écueil ?', 'Qu’allez-vous devoir désapprendre ?'],
    looks: [
      'Une conscience fine : automatismes, habitudes de service, difficulté à changer de posture',
      'Une stratégie pour rester en position d’apprentissage',
    ],
    avoid: ['« Mon expérience ne peut que m’aider »', 'Une réponse qui nie tout risque'],
    crit: [C.analyse, C.metier],
  }),

  // ---------------------------------------------------------------- O11 ---
  build({
    id: 'O11-1',
    skill: 'O11',
    axis: 'Imprévu',
    q: 'Je vous pose une question dont vous ne connaissez pas la réponse. Que faites-vous ?',
    follow: ['Comment vérifieriez-vous ensuite ?', 'Est-ce que dire « je ne sais pas » vous met mal à l’aise ?'],
    looks: [
      'Dire qu’on ne sait pas, sans s’effondrer',
      'Proposer une démarche de vérification',
      'Éventuellement, donner ce qu’on sait autour de la question',
    ],
    avoid: ['Inventer une réponse', 'Rester silencieuse sans rien proposer', 'S’excuser longuement'],
    crit: [C.analyse, C.organisation],
    sec: 120,
  }),
  build({
    id: 'O11-2',
    skill: 'O11',
    axis: 'Imprévu',
    q: 'Selon vous, quel est le principal enjeu de santé publique aujourd’hui ?',
    level: 'epreuve',
    follow: ['Pourquoi celui-là plutôt qu’un autre ?', 'Quel rôle une infirmière peut-elle y jouer ?'],
    looks: [
      'Un choix assumé et justifié, plutôt qu’une réponse attendue',
      'Des mécanismes expliqués, sans chiffres inventés',
      'Un lien avec la pratique professionnelle',
    ],
    avoid: ['Citer un chiffre dont vous n’êtes pas sûre', 'Une position partisane', 'Rester dans la généralité'],
    crit: [C.metier, C.analyse],
  }),
  build({
    id: 'O11-3',
    skill: 'O11',
    axis: 'Imprévu',
    q: 'Comment vérifiez-vous une information de santé que vous lisez ou qu’on vous rapporte ?',
    follow: ['Quelles sources considérez-vous comme fiables ?', 'Que faites-vous si une personne accompagnée vous rapporte une information fausse ?'],
    looks: ['Des critères : auteur, date, source primaire', 'Des sources institutionnelles citées', 'Une manière respectueuse de corriger une information'],
    avoid: ['Se fier aux réseaux sociaux', 'Contredire sèchement une personne'],
    crit: [C.metier, C.analyse],
  }),
  build({
    id: 'O11-4',
    skill: 'O11',
    axis: 'Imprévu',
    q: 'On vous dit que votre projet est trop ambitieux. Que répondez-vous ?',
    level: 'epreuve',
    follow: ['Qu’est-ce qui vous rend confiante ?', 'Qu’est-ce qui, objectivement, sera difficile ?'],
    looks: ['Une réponse calme, ni défensive ni résignée', 'Des arguments factuels', 'La reconnaissance des difficultés réelles'],
    avoid: ['Se justifier de façon défensive', 'Abandonner sa position à la première objection'],
    crit: [C.motivation, C.analyse],
  }),
  build({
    id: 'O11-5',
    skill: 'O11',
    axis: 'Imprévu',
    q: 'Avez-vous une question à nous poser ?',
    follow: [],
    looks: ['Une question préparée, précise et professionnelle', 'Une question qui montre l’intérêt pour la formation ou l’institut'],
    avoid: ['« Non, je n’ai pas de question »', 'Une question dont la réponse est sur le site de l’institut', 'Une question uniquement sur les résultats'],
    crit: [C.motivation, C.organisation],
    sec: 90,
  }),

  // ---------------------------------------------------------------- O12 ---
  build({
    id: 'O12-1',
    skill: 'O12',
    axis: 'Simulation',
    q: 'Simulation complète : présentez-vous en cinq minutes, puis répondez aux relances pendant quinze minutes.',
    level: 'epreuve',
    follow: [
      'Vous avez évoqué votre expérience : quel a été votre rôle exact dans la situation citée ?',
      'Pourquoi infirmière plutôt que de rester aide-soignante ?',
      'Qu’est-ce qui sera le plus difficile dans la formation ?',
      'Comment le financement est-il assuré ?',
      'Racontez une situation où vous vous êtes trompée.',
      'Qu’est-ce que vous ne savez pas encore de la formation ?',
    ],
    looks: [
      'Une cohérence d’ensemble entre les réponses',
      'Un temps tenu sur les vingt minutes',
      'La capacité à rebondir sans perdre le fil',
    ],
    avoid: ['Se contredire d’une réponse à l’autre', 'Dépasser largement le temps de présentation', 'Réciter un texte appris'],
    frame: FRAME_RECIT,
    crit: [C.parcours, C.motivation, C.metier, C.analyse, C.organisation],
    sec: 1200,
  }),
  build({
    id: 'O12-2',
    skill: 'O12',
    axis: 'Simulation',
    q: 'Simulation courte : présentez-vous en deux minutes, puis répondez à trois relances.',
    follow: [
      'Qu’est-ce qui, dans votre parcours, explique le mieux ce projet ?',
      'Quelle différence voyez-vous entre les deux métiers ?',
      'Comment vous organiserez-vous pendant la formation ?',
    ],
    looks: ['Une présentation dense et tenue', 'Des réponses directes aux relances', 'Une cohérence avec la présentation'],
    avoid: ['Répéter la présentation dans les relances', 'Dépasser le temps'],
    crit: [C.parcours, C.motivation, C.organisation],
    sec: 480,
  }),
  build({
    id: 'O12-3',
    skill: 'O12',
    axis: 'Simulation',
    q: 'Simulation avec relances difficiles : présentez-vous, puis répondez à des questions de mise en difficulté.',
    level: 'epreuve',
    follow: [
      'Vous n’avez pas le baccalauréat : qu’est-ce qui nous garantit que vous suivrez ?',
      'Vous dites aimer le contact humain : en quoi est-ce différent de votre métier actuel ?',
      'Que ferez-vous si votre employeur revient sur son accord ?',
      'Qu’est-ce que vous ne savez pas faire aujourd’hui et qui sera exigé ?',
    ],
    looks: ['Le maintien du calme', 'Des réponses argumentées, sans agressivité ni effondrement', 'La reconnaissance des points faibles avec un plan'],
    avoid: ['Se braquer', 'Se dévaloriser', 'Éluder les questions'],
    crit: [C.analyse, C.motivation, C.organisation],
    sec: 900,
  }),
  build({
    id: 'O12-4',
    skill: 'O12',
    axis: 'Simulation',
    q: 'Entraînement au temps : présentez votre projet en exactement trois minutes.',
    follow: ['Qu’avez-vous dû couper ?', 'Qu’est-ce qui était indispensable ?'],
    looks: ['Une durée réellement tenue', 'Des choix de contenu assumés', 'Une fin nette, sans délayage'],
    avoid: ['Terminer en 1 minute 30', 'Dépasser 4 minutes', 'Accélérer à la fin pour tout dire'],
    crit: [C.organisation, C.motivation],
    sec: 180,
  }),
  build({
    id: 'O12-5',
    skill: 'O12',
    axis: 'Simulation',
    q: 'Simulation sans préparation : une question est tirée au hasard, vous répondez immédiatement pendant deux minutes.',
    level: 'epreuve',
    follow: ['Comment avez-vous structuré votre réponse pendant que vous parliez ?', 'Qu’auriez-vous ajouté avec trente secondes de plus ?'],
    looks: ['Une structure malgré l’absence de préparation', 'Un début, un développement, une conclusion', 'Pas de panique visible'],
    avoid: ['Commencer sans savoir où l’on va', 'S’arrêter au bout de vingt secondes'],
    crit: [C.analyse, C.organisation],
    sec: 120,
  }),
]
